# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

a=32
if a<0:
  print("a is negative")
else:
  print("a is positive")

a=23
b=32
if a>b:
  print("The Greater Number is =",(a))
else:
  print("The Greater Number is =",(b))

a=45
if a%2==0:
  print("The number is Even")
else:
  print("The number is odd")

a=20
b=10
c=32
if a>b and a>c:
  print("The greatest number is =",(a))
elif b>a and b>c:
  print("The greatest number is=",(b))
else:
  print("The greatest number is =",(c))